set_property IOSTANDARD LVCMOS33 [get_ports j]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports k]
set_property IOSTANDARD LVCMOS33 [get_ports q]
set_property PACKAGE_PIN Y9  [get_ports clk]
set_property PACKAGE_PIN M15 [get_ports j]
set_property PACKAGE_PIN H17 [get_ports k]
set_property PACKAGE_PIN U14 [get_ports q]
